version: '3.9'
services:
  backend:
    build: ./backend
    container_name: saas_backend
    ports:
      - "3000:3000"
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  frontend:
    build: ./frontend
    container_name: saas_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://${BACK_DOMAIN}:3000

  caddy:
    image: caddy:2-alpine
    container_name: saas_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend